"""Regenerate the four generated index files for the git pre-commit hook.

The four files carry hand-written prose beside their generator-owned blocks. The
hook regenerates the blocks and stages the files, but must never sweep a bystander's
uncommitted prose into the commit. So this decides per file whether the worktree
differs from the index *outside* the generated blocks: if it does, it aborts and
touches nothing; otherwise it regenerates and stages. Any abort after the
generators have started restores the files, so a failed run leaves the worktree
exactly as it was found.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path
from typing import Mapping, Sequence

# (path, expected marker keys in file order). The keys mirror the four generators;
# a file without exactly these pairs is treated as foreign and left alone.
GENERATED_FILES: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("STRUCTURE.md", ("AUTO-STRUCTURE",)),
    ("tests/AGENTS.md", ("AUTO-STRUCTURE-TESTS",)),
    ("docs/AGENTS.md", ("AUTO-INDEX",)),
    (
        "docs/diataxis/reference/coding_standards/guardrails.md",
        ("AUTO-GUARDRAILS: clippy", "AUTO-GUARDRAILS: arch-lint", "AUTO-GUARDRAILS: syn"),
    ),
)

# (script, human label); run in this order, matching the original hook.
GENERATORS: tuple[tuple[str, str], ...] = (
    ("scripts/generate_docs_index.py", "docs index generation"),
    ("scripts/generate_guardrails_doc.py", "guardrails doc generation"),
    ("scripts/generate_structure_index.py", "structure index generation"),
    ("scripts/generate_tests_structure_index.py", "tests structure index generation"),
)

_MARKER = re.compile(r"^\s*<!--\s*(?P<key>.+?)\s+(?P<kind>START|END)\s*-->\s*$")


def parse_regions(lines: Sequence[str], keys: Sequence[str]) -> list[tuple[int, int]] | None:
    """Return the (first, last) line index of each expected marker pair.

    Returns None unless the file carries exactly the expected pairs, in order,
    with no extra or out-of-order markers.
    """
    markers: list[tuple[int, str, str]] = []
    for index, line in enumerate(lines):
        match = _MARKER.match(line)
        if match:
            markers.append((index, match.group("key"), match.group("kind")))

    expected = [(key, kind) for key in keys for kind in ("START", "END")]
    if [(key, kind) for _, key, kind in markers] != expected:
        return None

    return [(markers[i][0], markers[i + 1][0]) for i in range(0, len(markers), 2)]


def split_prose(text: str, keys: Sequence[str]) -> str | None:
    """Return `text` with every expected marker pair and its body removed.

    Returns None when the marker structure is not exactly as expected, so the
    caller cannot tell generated bytes from hand-written ones.
    """
    lines = text.splitlines(keepends=True)
    regions = parse_regions(lines, keys)
    if regions is None:
        return None
    removed = {index for start, end in regions for index in range(start, end + 1)}
    return "".join(line for index, line in enumerate(lines) if index not in removed)


def _read_worktree(root: Path, rel: str) -> bytes | None:
    try:
        return (root / rel).read_bytes()
    except OSError:
        return None


def _read_index(root: Path, rel: str) -> bytes | None:
    proc = subprocess.run(
        ["git", "-C", str(root), "show", f":{rel}"], capture_output=True
    )
    return proc.stdout if proc.returncode == 0 else None


def _snapshot(root: Path, rels: Sequence[str]) -> dict[str, bytes | None]:
    return {rel: _read_worktree(root, rel) for rel in rels}


def _restore(root: Path, snapshot: Mapping[str, bytes | None]) -> None:
    for rel, data in snapshot.items():
        path = root / rel
        if data is None:
            path.unlink(missing_ok=True)
        else:
            path.write_bytes(data)


def _prose(text: bytes | None, keys: Sequence[str]) -> str | None:
    if text is None:
        return None
    return split_prose(text.decode("utf-8", "surrogateescape"), keys)


def _diagnose(root: Path, rel: str, keys: tuple[str, ...]) -> tuple[str | None, bool]:
    """Return (problem, region_changed) for one generated file.

    `problem` is None when the file is safe to regenerate. `region_changed` is
    True when the uncommitted change lies entirely inside the generated block.
    """
    worktree = _read_worktree(root, rel)
    index = _read_index(root, rel)
    if worktree is None or index is None:
        return (
            f"{rel} is not committed yet, so this hook cannot regenerate it safely.\n"
            f"  git add {rel}",
            False,
        )
    worktree_prose = _prose(worktree, keys)
    index_prose = _prose(index, keys)
    if worktree_prose is None or index_prose is None:
        return (
            f"{rel} does not carry the expected generated-block markers "
            f"({', '.join(keys)}), so this hook cannot regenerate it safely.\n"
            f"  Restore the markers or stage your edits, then commit again: git add {rel}",
            False,
        )
    if worktree_prose != index_prose:
        return (
            f"{rel} has edits outside its generated block, so this hook cannot "
            f"safely re-stage it.\n"
            f"  Stage or stash those edits first, then commit again: git add {rel}",
            False,
        )
    return None, worktree != index


def run(
    root: Path,
    files: Sequence[tuple[str, tuple[str, ...]]] = GENERATED_FILES,
    generators: Sequence[tuple[str, str]] = GENERATORS,
) -> int:
    """Regenerate and stage the generated files, or abort without changing them."""
    root = Path(root)
    rels = [rel for rel, _ in files]

    problems: list[str] = []
    notes: list[str] = []
    for rel, keys in files:
        problem, region_changed = _diagnose(root, rel, keys)
        if problem is not None:
            problems.append(problem)
        elif region_changed:
            notes.append(
                f"regenerated {rel} (its generated block carried uncommitted changes)"
            )

    if problems:
        for problem in problems:
            print("")
            print(problem)
        return 1

    snapshot = _snapshot(root, rels)

    for script, label in generators:
        proc = subprocess.run([sys.executable, script], cwd=root)
        if proc.returncode != 0:
            _restore(root, snapshot)
            print("", file=sys.stderr)
            print(f"{label} failed; restored the generated files.", file=sys.stderr)
            return 1

    add = subprocess.run(
        ["git", "-C", str(root), "add", "--", *rels], capture_output=True
    )
    if add.returncode != 0:
        _restore(root, snapshot)
        print("", file=sys.stderr)
        print(
            "staging the regenerated files failed; restored them.",
            file=sys.stderr,
        )
        print(add.stderr.decode("utf-8", "replace").rstrip(), file=sys.stderr)
        return 1

    for note in notes:
        print(note)
    return 0


def main() -> int:
    """Resolve the repository root and run the pre-commit regeneration."""
    try:
        proc = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        print(f"pre-commit: could not resolve the repository root: {exc}", file=sys.stderr)
        return 1
    return run(Path(proc.stdout.strip()))


if __name__ == "__main__":
    sys.exit(main())
